<a href="https://colab.research.google.com/github/ahmad292910/Machine-Learning/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3,6,8])

In [3]:
arr.shape

(5,)

In [4]:
arr.ndim

1

In [5]:
arr.size

5

In [6]:
arr.itemsize

8

In [9]:
arr.dtype

dtype('int64')

In [13]:
arr=arr.astype('float')

In [14]:
arr.dtype

dtype('float64')

In [15]:
arr0=np.array(12)

In [16]:
arr0.ndim

0

In [17]:
arr1=np.array([1,2,3])

In [18]:
arr1.ndim

1

In [19]:
arr2=np.array([[1,2,3],[1,3,6]])

In [20]:
arr2.ndim

2

In [21]:
arr3=np.array([[[1,2,3]]])

In [22]:
arr3.ndim

3

In [23]:
arr4=np.array([[[[1,2,3]]]])

In [24]:
arr4.ndim

4

In [25]:
arr1.ravel()

array([1, 2, 3])

In [26]:
arr4=arr4.ravel()

In [27]:
arr4.ndim

1

In [28]:
arr1=arr1.reshape(1,3)

In [29]:
arr1.ndim

2

In [30]:
arr1.T

array([[1],
       [2],
       [3]])

In [31]:
s="My name is Ahmad"

In [32]:
s[0:7]

'My name'

In [33]:
s[3:10]

'name is'

In [34]:
s[: :2]

'M aei ha'

In [35]:
s[: :-1]

'damhA si eman yM'

In [37]:
arr5=np.arange(24).reshape(6,4)

In [38]:
arr5

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [39]:
arr5[4:6,2:4]

array([[18, 19],
       [22, 23]])

In [41]:
for i in arr5:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [43]:
arr6=np.arange(16).reshape(4,4)

In [44]:
arr6

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [47]:
arr6.min()

0

In [48]:
arr6.max()

15

In [49]:
arr6.mean()

7.5

In [52]:
np.median(arr6)

7.5

In [53]:
np.sin(arr6)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849, -0.54402111, -0.99999021],
       [-0.53657292,  0.42016704,  0.99060736,  0.65028784]])